// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAssWTKq5XfY_CsYL0SxJ-gPm8UUaSyR8w',
    appId: '1:324796910896:web:b6acc83876d6f4eae98cf5',
    messagingSenderId: '324796910896',
    projectId: 'generative-language-test',
    authDomain: 'generative-language-test.firebaseapp.com',
    storageBucket: 'generative-language-test.appspot.com',
    measurementId: 'G-26G42SVRHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUv9gbEFDgeTUZEWMQ7sd9ULDaB4fzEQA',
    appId: '1:324796910896:android:055f33ddec0c588ae98cf5',
    messagingSenderId: '324796910896',
    projectId: 'generative-language-test',
    storageBucket: 'generative-language-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhnLBGgKyqTeVNWy5Cdz2rQqtQQQAaHwQ',
    appId: '1:324796910896:ios:210391ebd34cb23ae98cf5',
    messagingSenderId: '324796910896',
    projectId: 'generative-language-test',
    storageBucket: 'generative-language-test.appspot.com',
    iosBundleId: 'com.example.generativeLanguageTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhnLBGgKyqTeVNWy5Cdz2rQqtQQQAaHwQ',
    appId: '1:324796910896:ios:210391ebd34cb23ae98cf5',
    messagingSenderId: '324796910896',
    projectId: 'generative-language-test',
    storageBucket: 'generative-language-test.appspot.com',
    iosBundleId: 'com.example.generativeLanguageTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAssWTKq5XfY_CsYL0SxJ-gPm8UUaSyR8w',
    appId: '1:324796910896:web:1d5c811e706b7a0ce98cf5',
    messagingSenderId: '324796910896',
    projectId: 'generative-language-test',
    authDomain: 'generative-language-test.firebaseapp.com',
    storageBucket: 'generative-language-test.appspot.com',
    measurementId: 'G-7WVJKM2GF3',
  );

}